; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Roblox FFlag Manager"
; Kept in sync with version.json by scripts/update_version.py at release time.
#define MyAppVersion "4.2.0"
#define MyAppPublisher "4anti"
#define MyAppURL "https://github.com/4anti/Roblox-Fastflag-Manager"
#define MyAppExeName "FFM.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AA0B1C-FF4A-4B6E-A533-1D0A4F6A2D1F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; The PyInstaller build is 64-bit. Without these, a 64-bit app installs in
; 32-bit mode on 64-bit Windows and lands in "Program Files (x86)".
; "x64compatible" is the Inno Setup 6.3+ identifier (also covers ARM64 x64 emulation).
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=FFM_Installer
SetupIconFile=ffm_v3_logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

; --- CRITICAL ONE-CLICK FEATURES ---
; Close the app automatically if it's running before installing/uninstalling
CloseApplications=yes
AppMutex=FFlagManager_SingleInstance_Mutex

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[InstallDelete]
; CLEAN UPGRADE FIX: wipe the previous install's files before copying the new
; build. PyInstaller one-dir apps break when upgraded in place because stale
; files in the old payload (DLLs / .pyd / modules in _internal) collide with the
; new build and crash it on launch. Removing the old folder contents first gives
; every install a clean slate.
; SAFE: all user data (settings, presets, flag history) lives in ~/.FFlagManager,
; NEVER in {app}, so nothing of the user's is touched here.
Type: filesandordirs; Name: "{app}\_internal"
Type: filesandordirs; Name: "{app}\*"

[UninstallDelete]
; Belt-and-suspenders clean install folder wipe. Inno normally removes files it
; tracked, but stray runtime files (crash logs, partial PyInstaller extracts,
; anything the running app dropped in {app}) can leave the folder behind. The
; explicit "{app}" entry forces a recursive delete at uninstall completion so
; C:\Program Files\Roblox FFlag Manager\ actually goes away every time.
Type: filesandordirs; Name: "{app}\*"
Type: dirifempty;    Name: "{app}"

[Files]
; This takes the output from PyInstaller (dist/FFM/*)
Source: "dist\FFM\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait

[Code]
var
  RemoveSettings: Boolean;
  RemovePresets: Boolean;
  RemoveCustomFlags: Boolean;
  RemoveHistory: Boolean;
  RemoveCaches: Boolean;
  UserDataBox: TNewCheckListBox;
  UserDataPage, DetailsPage: TNewNotebookPage;
  UninstallButton, DetailsBtn: TNewButton;
  OrigPageName, OrigPageDesc: String;
  OrigCancelEnabled: Boolean;
  OrigCancelModal: Integer;

procedure TryDeleteFile(const Path: String);
begin
  if FileExists(Path) then
    DeleteFile(Path);
end;

procedure WipeUserLogs(const UserDir: String);
var
  LogsDir: String;
begin
  LogsDir := UserDir + '\logs';
  if DirExists(LogsDir) then
    DelTree(LogsDir, True, True, True);
end;

procedure WipeUserSettings(const UserDir: String);
begin
  TryDeleteFile(UserDir + '\settings.json');
  TryDeleteFile(UserDir + '\last_version.txt');
  TryDeleteFile(UserDir + '\install.id');
  TryDeleteFile(UserDir + '\install.id.tmp');
end;

procedure WipeUserPresets(const UserDir: String);
begin
  TryDeleteFile(UserDir + '\presets.json');
end;

procedure WipeUserCustomFlags(const UserDir: String);
begin
  TryDeleteFile(UserDir + '\user_flags.json');
end;

procedure WipeUserHistory(const UserDir: String);
begin
  TryDeleteFile(UserDir + '\fflags_history.json');
end;

procedure WipeUserCaches(const UserDir: String);
var
  I: Integer;
begin
  TryDeleteFile(UserDir + '\known_flags.json');
  TryDeleteFile(UserDir + '\FFlags.h');
  TryDeleteFile(UserDir + '\offsets_cache.json');
  for I := 1 to 10 do
    TryDeleteFile(UserDir + '\offsets_cache_v' + IntToStr(I) + '.json');
  TryDeleteFile(UserDir + '\download_hashcache.json');
  TryDeleteFile(UserDir + '\join_fastpath.json');
end;

procedure WipeUserData(const DoSettings, DoPresets, DoCustomFlags, DoHistory, DoCaches: Boolean);
var
  UserDir: String;
begin
  UserDir := ExpandConstant('{%USERPROFILE}\.FFlagManager');
  if not DirExists(UserDir) then
    Exit;

  WipeUserLogs(UserDir);

  if DoSettings then
    WipeUserSettings(UserDir);
  if DoPresets then
    WipeUserPresets(UserDir);
  if DoCustomFlags then
    WipeUserCustomFlags(UserDir);
  if DoHistory then
    WipeUserHistory(UserDir);
  if DoCaches then
    WipeUserCaches(UserDir);

  RemoveDir(UserDir);
end;

procedure RemoveFFMHandler(const Scheme: String);
var
  Cmd: String;
begin
  if RegQueryStringValue(HKCU, 'Software\Classes\' + Scheme + '\shell\open\command', '', Cmd) then
  begin
    if (Pos('--roblox-handler', Cmd) > 0) or (Pos('FFM.exe', Cmd) > 0) then
      RegDeleteKeyIncludingSubkeys(HKCU, 'Software\Classes\' + Scheme);
  end;
end;

procedure ShowUserDataPage(Sender: TObject); forward;
procedure ShowDetailsPage(Sender: TObject); forward;

procedure FillDetailsList(Box: TNewCheckListBox);
begin
  Box.AddGroup('Always removed', 'logs\', 0, nil);
  Box.AddGroup('Application settings', 'settings.json, last_version.txt, install.id', 0, nil);
  Box.AddGroup('Saved presets', 'presets.json', 0, nil);
  Box.AddGroup('Custom flags', 'user_flags.json', 0, nil);
  Box.AddGroup('Flag history', 'fflags_history.json', 0, nil);
  Box.AddGroup('Caches', 'known_flags.json, FFlags.h, offsets_cache*.json, hash cache, join fast path', 0, nil);
  Box.AddGroup('Not offered', 'Roblox ClientAppSettings.json, Roblox install folders', 0, nil);
end;

procedure ShowUserDataPage(Sender: TObject);
begin
  UninstallProgressForm.InnerNotebook.ActivePage := UserDataPage;
  UninstallProgressForm.PageNameLabel.Caption := 'User data';
  UninstallProgressForm.PageDescriptionLabel.Caption :=
    'Choose extra files to remove from your profile.';
  UninstallButton.Visible := True;
  DetailsBtn.Caption := 'Details...';
  DetailsBtn.OnClick := @ShowDetailsPage;
end;

procedure ShowDetailsPage(Sender: TObject);
begin
  UninstallProgressForm.InnerNotebook.ActivePage := DetailsPage;
  UninstallProgressForm.PageNameLabel.Caption := 'Details';
  UninstallProgressForm.PageDescriptionLabel.Caption :=
    'Files under the user data folder.';
  UninstallButton.Visible := True;
  DetailsBtn.Caption := 'Back';
  DetailsBtn.OnClick := @ShowUserDataPage;
end;

procedure InitializeUninstallProgressForm();
var
  Intro, AlsoLbl, Footer: TNewStaticText;
  FolderImg: TBitmapImage;
  PathEdit: TNewEdit;
  DetailsBox: TNewCheckListBox;
  IconFile: String;
  Left, Width, NextTop, BtnW: Integer;
begin
  if UninstallSilent then
    Exit;

  OrigPageName := UninstallProgressForm.PageNameLabel.Caption;
  OrigPageDesc := UninstallProgressForm.PageDescriptionLabel.Caption;
  OrigCancelEnabled := UninstallProgressForm.CancelButton.Enabled;
  OrigCancelModal := UninstallProgressForm.CancelButton.ModalResult;

  IconFile := ExpandConstant('{app}\{#MyAppExeName}');
  if FileExists(IconFile) then
    InitializeBitmapImageFromIcon(
      UninstallProgressForm.WizardSmallBitmapImage, IconFile, clNone, [32, 48, 64]);

  BtnW := UninstallProgressForm.CancelButton.Width;
  UninstallButton := TNewButton.Create(UninstallProgressForm);
  UninstallButton.Parent := UninstallProgressForm;
  UninstallButton.Width := BtnW;
  UninstallButton.Height := UninstallProgressForm.CancelButton.Height;
  UninstallButton.Left :=
    UninstallProgressForm.CancelButton.Left - ScaleX(10) - UninstallButton.Width;
  UninstallButton.Top := UninstallProgressForm.CancelButton.Top;
  UninstallButton.Caption := 'Uninstall';
  UninstallButton.ModalResult := mrOk;
  UninstallButton.Default := True;
  UninstallButton.TabOrder := UninstallProgressForm.CancelButton.TabOrder;
  UninstallProgressForm.CancelButton.TabOrder := UninstallButton.TabOrder + 1;

  DetailsBtn := TNewButton.Create(UninstallProgressForm);
  DetailsBtn.Parent := UninstallProgressForm;
  DetailsBtn.Width := BtnW;
  DetailsBtn.Height := UninstallProgressForm.CancelButton.Height;
  DetailsBtn.Left := UninstallProgressForm.StatusLabel.Left;
  DetailsBtn.Top := UninstallProgressForm.CancelButton.Top;
  DetailsBtn.Caption := 'Details...';
  DetailsBtn.OnClick := @ShowDetailsPage;

  UserDataPage := TNewNotebookPage.Create(UninstallProgressForm);
  UserDataPage.Notebook := UninstallProgressForm.InnerNotebook;
  UserDataPage.Parent := UninstallProgressForm.InnerNotebook;
  UserDataPage.Align := alClient;

  DetailsPage := TNewNotebookPage.Create(UninstallProgressForm);
  DetailsPage.Notebook := UninstallProgressForm.InnerNotebook;
  DetailsPage.Parent := UninstallProgressForm.InnerNotebook;
  DetailsPage.Align := alClient;

  Left := UninstallProgressForm.StatusLabel.Left;
  Width := UninstallProgressForm.StatusLabel.Width;
  NextTop := UninstallProgressForm.StatusLabel.Top;

  Intro := TNewStaticText.Create(UninstallProgressForm);
  Intro.Parent := UserDataPage;
  Intro.Left := Left;
  Intro.Top := NextTop;
  Intro.Width := Width;
  Intro.AutoSize := True;
  Intro.WordWrap := True;
  Intro.ShowAccelChar := False;
  Intro.ParentFont := True;
  Intro.Caption :=
    'The program is always removed. Tick extra items to delete them too.';
  NextTop := Intro.Top + Intro.Height + ScaleY(10);

  FolderImg := TBitmapImage.Create(UninstallProgressForm);
  FolderImg.Parent := UserDataPage;
  FolderImg.Left := Left;
  FolderImg.Width := ScaleX(16);
  FolderImg.Height := ScaleY(16);
  FolderImg.BackColor := clNone;
  InitializeBitmapImageFromStockIcon(FolderImg, SIID_FOLDER, clNone, [16, 20, 24]);

  PathEdit := TNewEdit.Create(UninstallProgressForm);
  PathEdit.Parent := UserDataPage;
  PathEdit.Left := FolderImg.Left + FolderImg.Width + ScaleX(6);
  PathEdit.Top := NextTop;
  PathEdit.Width := Width - FolderImg.Width - ScaleX(6);
  PathEdit.Height := ScaleY(21);
  PathEdit.ReadOnly := True;
  PathEdit.Text := ExpandConstant('{%USERPROFILE}\.FFlagManager');
  FolderImg.Top := PathEdit.Top + ((PathEdit.Height - FolderImg.Height) div 2);
  NextTop := PathEdit.Top + PathEdit.Height + ScaleY(10);

  AlsoLbl := TNewStaticText.Create(UninstallProgressForm);
  AlsoLbl.Parent := UserDataPage;
  AlsoLbl.Left := Left;
  AlsoLbl.Top := NextTop;
  AlsoLbl.Width := Width;
  AlsoLbl.AutoSize := True;
  AlsoLbl.ShowAccelChar := False;
  AlsoLbl.ParentFont := True;
  AlsoLbl.Font.Style := [fsBold];
  AlsoLbl.Caption := 'Also remove:';
  NextTop := AlsoLbl.Top + AlsoLbl.Height + ScaleY(6);

  UserDataBox := TNewCheckListBox.Create(UninstallProgressForm);
  UserDataBox.Parent := UserDataPage;
  UserDataBox.Left := Left;
  UserDataBox.Top := NextTop;
  UserDataBox.Width := Width;
  UserDataBox.Height := ScaleY(5 * 22 + 10);
  UserDataBox.Flat := True;
  UserDataBox.ShowLines := False;
  UserDataBox.WantTabs := False;
  UserDataBox.MinItemHeight := ScaleY(22);
  UserDataBox.AddCheckBox('Application settings', 'Theme, window, options', 0, False, True, False, True, nil);
  UserDataBox.AddCheckBox('Saved presets', 'Preset packs', 0, False, True, False, True, nil);
  UserDataBox.AddCheckBox('Custom flags', 'Editor flag list', 0, False, True, False, True, nil);
  UserDataBox.AddCheckBox('Flag history', 'Undo snapshots', 0, False, True, False, True, nil);
  UserDataBox.AddCheckBox('Caches', 'Offsets, hashes, known flags', 0, False, True, False, True, nil);
  NextTop := UserDataBox.Top + UserDataBox.Height + ScaleY(8);

  Footer := TNewStaticText.Create(UninstallProgressForm);
  Footer.Parent := UserDataPage;
  Footer.Left := Left;
  Footer.Top := NextTop;
  Footer.Width := Width;
  Footer.AutoSize := True;
  Footer.WordWrap := True;
  Footer.ShowAccelChar := False;
  Footer.ParentFont := True;
  Footer.Font.Color := clGrayText;
  Footer.Caption := 'Roblox game files are not touched.';

  DetailsBox := TNewCheckListBox.Create(UninstallProgressForm);
  DetailsBox.Parent := DetailsPage;
  DetailsBox.Left := Left;
  DetailsBox.Top := UninstallProgressForm.StatusLabel.Top;
  DetailsBox.Width := Width;
  DetailsBox.Height := UninstallProgressForm.ProgressBar.Top +
    UninstallProgressForm.ProgressBar.Height - DetailsBox.Top;
  DetailsBox.Flat := True;
  DetailsBox.ShowLines := False;
  DetailsBox.WantTabs := False;
  DetailsBox.MinItemHeight := ScaleY(22);
  FillDetailsList(DetailsBox);

  UninstallProgressForm.CancelButton.Enabled := True;
  UninstallProgressForm.CancelButton.ModalResult := mrCancel;
  ShowUserDataPage(nil);

  UninstallProgressForm.Hide;
  if UninstallProgressForm.ShowModal = mrCancel then
    Abort;

  RemoveSettings := UserDataBox.Checked[0];
  RemovePresets := UserDataBox.Checked[1];
  RemoveCustomFlags := UserDataBox.Checked[2];
  RemoveHistory := UserDataBox.Checked[3];
  RemoveCaches := UserDataBox.Checked[4];

  UninstallButton.Visible := False;
  DetailsBtn.Visible := False;
  UninstallProgressForm.PageNameLabel.Caption := OrigPageName;
  UninstallProgressForm.PageDescriptionLabel.Caption := OrigPageDesc;
  UninstallProgressForm.CancelButton.Enabled := OrigCancelEnabled;
  UninstallProgressForm.CancelButton.ModalResult := OrigCancelModal;
  UninstallProgressForm.InnerNotebook.ActivePage :=
    UninstallProgressForm.InstallingPage;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usUninstall then
  begin
    RemoveFFMHandler('roblox-player');
    RemoveFFMHandler('roblox');
  end;

  if CurUninstallStep = usPostUninstall then
    WipeUserData(RemoveSettings, RemovePresets, RemoveCustomFlags, RemoveHistory, RemoveCaches);
end;
