import {useEffect,useMemo,useRef,useState} from 'react';
import {Icon} from '../components/Icons';
import CustomSelect from '../components/CustomSelect';
import Modal from '../components/Modal';
import InfoTooltip from '../components/InfoTooltip';
import {callDesktop} from '../lib/desktopApi';
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const rule=()=>({id:uid(),assetId:'',mode:'asset',replacement:'',enabled:true});
const modes=[{value:'asset',label:'Asset ID',detail:'Redirect to another Roblox asset'},{value:'url',label:'HTTPS URL',detail:'Serve a remote replacement'},{value:'file',label:'Local file',detail:'Serve a file on this computer'},{value:'remove',label:'Remove asset',detail:'Block the request'}];
const clean=p=>({id:String(p?.id||uid()),version:1,name:String(p?.name||'Default profile').slice(0,60),rules:Array.isArray(p?.rules)?p.rules.slice(0,500).map(x=>({...rule(),...x,assetId:String(x.assetId||'').replace(/\D/g,''),replacement:String(x.replacement||'')})):[]});
export default function AssetProxyView({notify}){
 const [profiles,setProfiles]=useState([clean({})]),[activeId,setActiveId]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState(null),[tab,setTab]=useState('single'),[bulk,setBulk]=useState(''),[draft,setDraft]=useState(rule()),[clearOpen,setClearOpen]=useState(false),[profileModal,setProfileModal]=useState(''),[profileName,setProfileName]=useState(''),[actionsOpen,setActionsOpen]=useState(false),[addOpen,setAddOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[syncing,setSyncing]=useState(false),[loaded,setLoaded]=useState(false),[context,setContext]=useState(null),[gamesOpen,setGamesOpen]=useState(false),[games,setGames]=useState([]),[gameQuery,setGameQuery]=useState(''),[selectedGame,setSelectedGame]=useState(null),[scraped,setScraped]=useState([]),[scrapedPath,setScrapedPath]=useState(""),[scrapedLoading,setScrapedLoading]=useState(false);
 const importRef=useRef(),actionsRef=useRef(),splitRef=useRef(),profile=profiles.find(p=>p.id===activeId)||profiles[0];
 const update=fn=>setProfiles(all=>all.map(p=>p.id===profile.id?fn(p):p));
 useEffect(()=>{(async()=>{const result=await callDesktop('get_asset_proxy_profile');try{const lib=JSON.parse(localStorage.getItem('meowware.proxyProfiles')||'null');if(lib?.profiles?.length){const all=lib.profiles.map(clean);setProfiles(all);setActiveId(all.some(p=>p.id===lib.activeId)?lib.activeId:all[0].id)}else{const p=clean(result?.profile||{});setProfiles([p]);setActiveId(p.id)}}catch{const p=clean(result?.profile||{});setProfiles([p]);setActiveId(p.id)}setLoaded(true)})()},[]);
 useEffect(()=>{if(!loaded)return;localStorage.setItem('meowware.proxyProfiles',JSON.stringify({activeId:profile.id,profiles}));const t=setTimeout(()=>callDesktop('save_asset_proxy_profile',profile),180);return()=>clearTimeout(t)},[profiles,activeId,loaded]);
 useEffect(()=>{const close=e=>{if(!actionsRef.current?.contains(e.target))setActionsOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 useEffect(()=>{const close=e=>{if(!splitRef.current?.contains(e.target)){setAddOpen(false);setImportOpen(false)}};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[]);
 useEffect(()=>{const close=()=>setContext(null);window.addEventListener('pointerdown',close);window.addEventListener('blur',close);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('blur',close)}},[]);
 useEffect(()=>{const pending=sessionStorage.getItem('vellium.pendingAssetId');if(pending){sessionStorage.removeItem('vellium.pendingAssetId');setEditing('new');setTab('single');setDraft({...rule(),assetId:pending});setBulk('')}},[]);
 const visible=useMemo(()=>profile.rules.filter(x=>`${x.assetId} ${x.replacement} ${x.mode}`.toLowerCase().includes(query.toLowerCase())),[profile.rules,query]);
 const valid=/^\d+$/.test(draft.assetId)&&(draft.mode==='remove'||draft.mode==='asset'&&/^\d+$/.test(draft.replacement)||draft.mode==='url'&&/^https:\/\//i.test(draft.replacement)||draft.mode==='file'&&draft.replacement.trim());
 const bulkRules=useMemo(()=>bulk.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const [a,...r]=line.split(/\s*(?:=>|=)\s*/),v=r.join('=');if(!/^\d+$/.test(a))return null;if(!v)return{...rule(),assetId:a,mode:'remove'};if(/^\d+$/.test(v))return{...rule(),assetId:a,replacement:v};if(/^https:\/\//i.test(v))return{...rule(),assetId:a,mode:'url',replacement:v};return null}).filter(Boolean),[bulk]);
 const open=x=>{setEditing(x?.id||'new');setTab('single');setDraft(x?{...x}:rule());setBulk('')};
 const openAddMode=mode=>{setEditing('new');setTab(mode);setDraft(rule());setBulk('');setAddOpen(false)};
 const save=()=>{if(tab==='bulk'){if(!bulkRules.length)return;update(p=>({...p,rules:[...p.rules,...bulkRules]}));notify(`${bulkRules.length} replacements added`)}else{if(!valid)return;update(p=>({...p,rules:editing==='new'?[...p.rules,draft]:p.rules.map(x=>x.id===editing?draft:x)}));notify('Replacement saved')}setEditing(null)};
 const choose=async()=>{const r=await callDesktop('choose_asset_proxy_file');if(r?.ok)setDraft(d=>({...d,replacement:r.path}));else document.getElementById('proxy-file')?.click()};
 const importFile=f=>{if(!f)return;const r=new FileReader;r.onload=()=>{try{const p=clean(JSON.parse(r.result));setProfiles(a=>[...a,p]);setActiveId(p.id);notify('Vellium Proxy profile imported')}catch{notify('Invalid profile JSON')}};r.readAsText(f)};
 const exportFile=()=>{const b=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`${profile.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'meow-proxy'}.json`;a.click();URL.revokeObjectURL(u)};
 const saveName=()=>{const name=profileName.trim();if(!name)return;if(profileModal==='new'){const p=clean({name});setProfiles(a=>[...a,p]);setActiveId(p.id)}else update(p=>({...p,name}));setProfileModal('')};
 const removeProfile=()=>{if(profiles.length===1)return;const all=profiles.filter(p=>p.id!==profile.id);setProfiles(all);setActiveId(all[0].id);setActionsOpen(false)};
 const sync=async launch=>{setSyncing(true);const r=await callDesktop('apply_asset_proxy_profile',profile,launch);setSyncing(false);if(!r)return notify('Desktop bridge unavailable');notify(r.ok?(r.launched?`Vellium Proxy started with ${r.count} rules`:r.runtime_missing?`Synced ${r.count} rules; proxy runtime missing`:`Synced ${r.count} rules`):(r.error||'Sync failed'))};
 const openGames=async()=>{setGamesOpen(true);setScrapedLoading(true);const r=await callDesktop('get_meow_proxy_scraped_games');setGames(r?.games||[]);setScrapedLoading(false)};
 const loadGame=async game=>{setSelectedGame(game);setScraped([]);setScrapedPath("");setScrapedLoading(true);const r=await callDesktop('get_meow_proxy_scraped_assets',game.assets_url||game.replacements_url);setScraped(r?.assets||[]);setScrapedLoading(false);if(!r?.ok)notify(r?.error||'Could not load scraped assets')};
 const addScraped=asset=>{setEditing('new');setTab('single');setDraft({...rule(),assetId:asset.id});setGamesOpen(false)};
 const Tip=({text,children})=><InfoTooltip width={210} content={<div className="proxy-button-tip"><strong>{text}</strong><span>Vellium Proxy action</span></div>}>{children}</InfoTooltip>;
 const folderPrefix=scrapedPath?`${scrapedPath} / `:'';
 const scrapedFolders=[...new Set(scraped.map(a=>a.path||'').filter(path=>path.startsWith(folderPrefix)&&path!==scrapedPath).map(path=>path.slice(folderPrefix.length).split(' / ')[0]).filter(Boolean))].sort();
 const scrapedHere=scraped.filter(a=>(a.path||'')===scrapedPath);
 return <div className="view asset-proxy-view">
  <header className="proxy-header"><div><span className="eyebrow">Vellium Proxy</span><h1>Asset replacements</h1><p>Redirect or remove Roblox assets through a local proxy profile.</p></div><div className="proxy-header-actions" ref={splitRef}><div className="proxy-actions-menu" ref={actionsRef}><button className="proxy-profile-plus" title="Profile actions" onClick={()=>setActionsOpen(x=>!x)}><Icon name="plus" size={15}/></button><div className={`proxy-actions-popover${actionsOpen?' visible':''}`}><span>Profile actions</span><button onClick={()=>{exportFile();setActionsOpen(false)}}><Icon name="export" size={13}/>Export profile</button><button onClick={()=>{setProfileName(profile.name);setProfileModal('rename');setActionsOpen(false)}}><Icon name="edit" size={13}/>Rename profile</button><button disabled={profiles.length===1} onClick={removeProfile}><Icon name="trash" size={13}/>Delete profile</button><button className="danger" disabled={!profile.rules.length} onClick={()=>{setClearOpen(true);setActionsOpen(false)}}><Icon name="x" size={13}/>Clear replacements</button></div></div><div className="proxy-split-button"><button className="btn split-main" onClick={()=>importRef.current?.click()}><Icon name="import" size={13}/>Import profile</button><button className="btn split-arrow" aria-label="Import options" onClick={()=>{setImportOpen(x=>!x);setAddOpen(false)}}><Icon name="chevron" size={11}/></button><div className={`proxy-split-menu${importOpen?' visible':''}`}><span>Import</span><button onClick={()=>{importRef.current?.click();setImportOpen(false)}}><Icon name="copy" size={13}/><i><strong>JSON profile</strong><small>Load a saved Vellium Proxy profile</small></i></button><button onClick={()=>{openGames();setImportOpen(false)}}><Icon name="database" size={13}/><i><strong>Scraped games</strong><small>Browse Fleasion asset databases</small></i></button></div></div><div className="proxy-split-button primary"><button className="btn primary split-main" onClick={()=>openAddMode('single')}><Icon name="plus" size={14}/>Add replacement</button><button className="btn primary split-arrow" aria-label="Add replacement options" onClick={()=>{setAddOpen(x=>!x);setImportOpen(false)}}><Icon name="chevron" size={11}/></button><div className={`proxy-split-menu${addOpen?' visible':''}`}><span>Add replacement</span><button onClick={()=>openAddMode('single')}><Icon name="plus" size={13}/><i><strong>Single</strong><small>Create one asset mapping</small></i></button><button onClick={()=>openAddMode('bulk')}><Icon name="list" size={13}/><i><strong>Bulk</strong><small>Paste several mappings at once</small></i></button></div></div></div></header>
  <section className="proxy-toolbar"><div className="proxy-profile-picker"><CustomSelect value={profile.id} options={profiles.map(p=>({value:p.id,label:p.name,detail:`${p.rules.length} replacements`}))} onChange={setActiveId}/><button className="proxy-profile-new" title="New profile" aria-label="Create new profile" onClick={()=>{setProfileName('');setProfileModal('new')}}><Icon name="plus" size={16}/></button></div><label className="proxy-search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search replacements"/></label><div className="proxy-summary"><strong>{profile.rules.filter(x=>x.enabled).length}</strong><span>active</span></div></section>
  <div className="proxy-workspace-grid"><section className="proxy-list-shell"><div className="proxy-list-head"><span>Source asset</span><span>Replacement</span><span>Type</span><span>Status</span><span/></div>{visible.length?<div className="proxy-rule-list">{visible.map(x=><article className="proxy-rule" key={x.id} onContextMenu={e=>{e.preventDefault();setContext({x:e.clientX,y:e.clientY,rule:x})}}><div className="proxy-asset-id"><Icon name="box" size={14}/><span><strong>{x.assetId}</strong><small>Roblox asset</small></span></div><code>{x.mode==='remove'?'Request blocked':x.replacement}</code><span className="proxy-type">{modes.find(m=>m.value===x.mode)?.label}</span><button className={`proxy-status${x.enabled?' enabled':''}`} onClick={()=>update(p=>({...p,rules:p.rules.map(r=>r.id===x.id?{...r,enabled:!r.enabled}:r)}))}><i/>{x.enabled?'Enabled':'Disabled'}</button><div className="proxy-row-actions"><Tip text="Edit replacement"><button onClick={()=>open(x)}><Icon name="edit" size={13}/></button></Tip><Tip text="Delete replacement"><button className="danger" onClick={()=>update(p=>({...p,rules:p.rules.filter(r=>r.id!==x.id)}))}><Icon name="trash" size={13}/></button></Tip></div></article>)}</div>:<div className="proxy-empty"><span><Icon name="route" size={22}/></span><h2>{query?'No matching replacements':'No replacements in this profile'}</h2><p>{query?'Try another search.':'Add one mapping or paste several in bulk.'}</p>{!query&&<button className="btn" onClick={()=>open()}><Icon name="plus" size={13}/>Add replacement</button>}</div>}</section><aside className="proxy-control-panel"><div><span className="eyebrow">Vellium Proxy</span><h2>Proxy control</h2><p>Sync this profile to the local proxy runtime.</p></div><dl><div><dt>Profile</dt><dd>{profile.name}</dd></div><div><dt>Enabled</dt><dd>{profile.rules.filter(x=>x.enabled).length}</dd></div><div><dt>Disabled</dt><dd>{profile.rules.filter(x=>!x.enabled).length}</dd></div></dl><div className="proxy-control-actions"><Tip text="Apply profile and start the local proxy"><button className="btn primary" disabled={syncing} onClick={()=>sync(true)}><Icon name="play" size={13}/>{syncing?'Starting…':'Apply & start'}</button></Tip><Tip text="Write the current rules to Fleasion"><button className="btn" disabled={syncing} onClick={()=>sync(false)}><Icon name="refresh" size={13}/>Sync changes</button></Tip><Tip text="Browse Fleasion's scraped-game database"><button className="btn" onClick={openGames}><Icon name="database" size={13}/>Scraped games</button></Tip><button className="btn" disabled={!profile.rules.length} onClick={()=>update(p=>({...p,rules:p.rules.map(x=>({...x,enabled:true}))}))}><Icon name="check" size={13}/>Enable all</button><button className="btn" disabled={!profile.rules.length} onClick={()=>update(p=>({...p,rules:p.rules.map(x=>({...x,enabled:false}))}))}><Icon name="minus" size={13}/>Disable all</button></div><small>Restart Roblox or clear its asset cache after changes.</small></aside></div>
  <input ref={importRef} hidden type="file" accept="application/json,.json" onChange={e=>importFile(e.target.files?.[0])}/><input id="proxy-file" hidden type="file" onChange={e=>setDraft(d=>({...d,replacement:e.target.files?.[0]?.name||''}))}/>
  <Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title={editing==='new'?'Add replacements':'Edit replacement'} subtitle="Add one mapping or paste several at once." width="650px" footer={<><button className="btn" onClick={()=>setEditing(null)}>Cancel</button><button className="btn primary" disabled={tab==='bulk'?!bulkRules.length:!valid} onClick={save}><Icon name="check" size={13}/>{tab==='bulk'?`Add ${bulkRules.length||''} replacements`:'Save replacement'}</button></>}><div className="modal-tabs"><button className={`modal-tab${tab==='single'?' active':''}`} onClick={()=>setTab('single')}>Single replacement</button>{editing==='new'&&<button className={`modal-tab${tab==='bulk'?' active':''}`} onClick={()=>setTab('bulk')}>Bulk paste</button>}</div>{tab==='single'?<div className="proxy-editor"><label><span>Source asset ID</span><div className="input-with-icon"><Icon name="box" size={14}/><input autoFocus value={draft.assetId} onChange={e=>setDraft(d=>({...d,assetId:e.target.value.replace(/\D/g,'')}))} placeholder="Roblox asset ID"/></div></label><label><span>Replacement type</span><CustomSelect value={draft.mode} options={modes} onChange={mode=>setDraft(d=>({...d,mode,replacement:mode==='remove'?'':d.replacement}))}/></label>{draft.mode!=='remove'&&<label><span>Replacement</span><div className="proxy-replacement-input"><input value={draft.replacement} onChange={e=>setDraft(d=>({...d,replacement:e.target.value}))} placeholder={draft.mode==='asset'?'Replacement asset ID':draft.mode==='url'?'https://…':'Choose a local file'}/>{draft.mode==='file'&&<button className="btn" onClick={choose}><Icon name="folder" size={13}/>Browse</button>}</div></label>}</div>:<div className="proxy-bulk-editor"><p>One per line: <code>source=destination</code>. Leave destination empty to remove.</p><textarea autoFocus value={bulk} onChange={e=>setBulk(e.target.value)} placeholder={'123456=987654\n234567=https://example.com/asset\n345678='}/><div><span>Detected</span><strong>{bulkRules.length} valid replacements</strong></div></div>}</Modal>
  <Modal open={clearOpen} onClose={()=>setClearOpen(false)} title="Clear replacements" width="390px" tone="danger" footer={<><button className="btn" onClick={()=>setClearOpen(false)}>Cancel</button><button className="btn danger" onClick={()=>{update(p=>({...p,rules:[]}));setClearOpen(false)}}><Icon name="trash" size={13}/>Clear all</button></>}><p className="modal-body-text">Remove every replacement from <strong>{profile.name}</strong>?</p></Modal>
  <Modal open={Boolean(profileModal)} onClose={()=>setProfileModal('')} title={profileModal==='new'?'New proxy profile':'Rename profile'} width="390px" footer={<><button className="btn" onClick={()=>setProfileModal('')}>Cancel</button><button className="btn primary" disabled={!profileName.trim()} onClick={saveName}><Icon name="check" size={13}/>{profileModal==='new'?'Create profile':'Save name'}</button></>}><label className="modal-field"><span className="label">Profile name</span><input autoFocus className="input" value={profileName} onChange={e=>setProfileName(e.target.value)} maxLength={60} placeholder="My replacements"/></label></Modal>
  <Modal open={gamesOpen} onClose={()=>setGamesOpen(false)} title="Scraped games" subtitle="Browse Fleasion's public asset databases." width="820px"><div className="scraped-browser"><aside><label><Icon name="search" size={13}/><input value={gameQuery} onChange={e=>setGameQuery(e.target.value)} placeholder="Search games"/></label>{scrapedLoading&&!games.length?<p>Loading catalog…</p>:games.filter(g=>g.name.toLowerCase().includes(gameQuery.toLowerCase())).map(g=><button className={selectedGame?.name===g.name?'active':''} key={g.name} disabled={!g.assets_url&&!g.replacements_url} onClick={()=>loadGame(g)}><Icon name="gamepad" size={13}/><span><strong>{g.name}</strong><small>{g.owner||'Community database'}</small></span><Icon name="chevron-right" size={12}/></button>)}</aside><section><header><strong>{scrapedPath||selectedGame?.name||'Choose a game'}</strong><span>{scrapedPath&&<button className='scraped-back' onClick={()=>setScrapedPath(scrapedPath.split(' / ').slice(0,-1).join(' / '))}><Icon name='chevron-right' size={11}/> Back</button>}{scraped.length?`${scraped.length} assets`:''}</span></header>{scrapedLoading&&selectedGame?<div className="scraped-empty">Loading asset database…</div>:scraped.length?<div className="scraped-assets">{scrapedFolders.map(folder=><button className="scraped-folder" key={folder} onClick={()=>setScrapedPath(folderPrefix+folder)}><span><strong>{folder}</strong><small>Folder</small></span><code>{scraped.filter(a=>(a.path||'').startsWith(folderPrefix+folder)).length} assets</code><Icon name="chevron-right" size={12}/></button>)}{scrapedHere.slice(0,1200).map((a,i)=><button key={`${a.id}-${i}`} onClick={()=>addScraped(a)}><span><strong>{a.name}</strong><small>{a.path||'Asset'}</small></span><code>{a.id}</code><Icon name="plus" size={12}/></button>)}</div>:<div className="scraped-empty">Select a game to browse its scraped assets.</div>}</section></div></Modal>
  {context&&<div className="proxy-context-menu" style={{left:context.x,top:context.y}} onPointerDown={e=>e.stopPropagation()}><span>Replacement {context.rule.assetId}</span><button onClick={()=>{open(context.rule);setContext(null)}}><Icon name="edit" size={13}/>Edit replacement</button><button onClick={()=>{navigator.clipboard.writeText(context.rule.assetId);setContext(null)}}><Icon name="copy" size={13}/>Copy source ID</button><button onClick={()=>{update(p=>({...p,rules:[...p.rules,{...context.rule,id:uid()}]}));setContext(null)}}><Icon name="copy" size={13}/>Duplicate rule</button><button onClick={()=>{update(p=>({...p,rules:p.rules.map(r=>r.id===context.rule.id?{...r,enabled:!r.enabled}:r)}));setContext(null)}}><Icon name="power" size={13}/>{context.rule.enabled?'Disable':'Enable'} rule</button><button className="danger" onClick={()=>{update(p=>({...p,rules:p.rules.filter(r=>r.id!==context.rule.id)}));setContext(null)}}><Icon name="trash" size={13}/>Delete rule</button></div>}
 </div>
}
