import {useCallback,useEffect,useMemo,useState} from 'react';
import {Icon} from '../components/Icons';
import Modal from '../components/Modal';
import CustomSelect from '../components/CustomSelect';
import {callDesktop} from '../lib/desktopApi';

const bytes=value=>{const n=Number(value)||0;return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`};
const clock=value=>{if(!value)return '—';const n=Number(value);if(Number.isFinite(n)){const d=new Date(n<1e12?n*1000:n);return d.toLocaleTimeString()}return String(value)};
export default function ProxyTrafficView({notify}){
 const [entries,setEntries]=useState([]),[query,setQuery]=useState(''),[method,setMethod]=useState('all'),[shown,setShown]=useState(50),[loading,setLoading]=useState(true),[preserving,setPreserving]=useState(true),[selected,setSelected]=useState(null),[detail,setDetail]=useState(null);
 const refresh=useCallback(async()=>{setLoading(true);const r=await callDesktop('get_vellium_proxy_traffic');if(r?.ok){setEntries(r.entries||[]);setPreserving(Boolean(r.preserving))}else notify(r?.error||'Could not load proxy traffic');setLoading(false)},[notify]);
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[refresh]);
 const methods=useMemo(()=>[{value:'all',label:'All methods'},...[...new Set(entries.map(e=>e.method).filter(Boolean))].sort().map(value=>({value,label:value}))],[entries]);
 const visible=useMemo(()=>{const needle=query.toLowerCase();return entries.filter(e=>(method==='all'||e.method===method)&&(!needle||`${e.method} ${e.host} ${e.path} ${e.status}`.toLowerCase().includes(needle)))},[entries,query,method]);
 useEffect(()=>setShown(50),[query,method]);
 const open=async entry=>{setSelected(entry);setDetail(null);const r=await callDesktop('get_vellium_proxy_traffic_detail',entry.id);setDetail(r)};
 return <div className="view traffic-view"><header className="proxy-header"><div><span className="eyebrow">Vellium Proxy</span><h1>Proxy traffic</h1><p>Inspect requests preserved by Fleasion's Roblox environment proxy.</p></div><div className={`traffic-preserve${preserving?' active':''}`}><i/><span><strong>{preserving?'Preserving traffic':'Preservation disabled'}</strong><small>{entries.length} saved requests</small></span></div></header><section className="traffic-toolbar"><label><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search host, path, method, or status"/></label><CustomSelect compact value={method} options={methods} onChange={setMethod}/><button className="btn" onClick={refresh}><Icon name="refresh" size={13}/>{loading?'Refreshing…':'Refresh'}</button></section><section className="traffic-shell"><div className="traffic-head"><span>Time</span><span>Method</span><span>Host</span><span>Path</span><span>Status</span><span>Size</span><span>Time</span></div>{visible.length?<div className="traffic-list" onScroll={e=>{const el=e.currentTarget;if(el.scrollTop+el.clientHeight>=el.scrollHeight-100)setShown(n=>Math.min(n+50,visible.length))}}>{visible.slice(0,shown).map(entry=><button className={`traffic-row${entry.intercepted?' intercepted':''}${entry.dropped?' dropped':''}`} key={entry.id} onClick={()=>open(entry)}><span>{clock(entry.time)}</span><strong>{entry.method||'—'}</strong><span>{entry.host||'—'}</span><code>{entry.path||'/'}</code><span className={`traffic-status s-${String(entry.status||'').charAt(0)}`}>{entry.dropped?'Dropped':entry.status||'Pending'}</span><span>{bytes(entry.size)}</span><span>{entry.ms?`${entry.ms} ms`:'—'}</span></button>)}</div>:<div className="proxy-empty"><span><Icon name="activity" size={22}/></span><h2>{loading?'Loading traffic':'No preserved traffic'}</h2><p>Enable Preserve proxy traffic in Settings, start the proxy, and launch Roblox.</p></div>}</section><Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={`${selected?.method||'Request'} ${selected?.host||''}`} subtitle={selected?.path||'/'} width="800px"><div className="traffic-detail"><div><span>Request</span><pre>{detail?.request||'No request body preserved.'}</pre></div><div><span>Response</span><pre>{detail?.response||'No response body preserved.'}</pre></div></div></Modal></div>
}
