import {useCallback,useEffect,useMemo,useState} from 'react';
import {Icon} from '../components/Icons';
import InfoTooltip from '../components/InfoTooltip';
import Modal from '../components/Modal';
import CustomSelect from '../components/CustomSelect';
import {callDesktop} from '../lib/desktopApi';

const formatBytes=value=>{const n=Number(value)||0;if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`};
const formatTime=value=>{if(!value)return 'Unknown time';const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toLocaleString()};

export default function ScraperView({notify,onNavigate}){
 const [assets,setAssets]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[auto,setAuto]=useState(true),[running,setRunning]=useState(false),[sourceFound,setSourceFound]=useState(false),[lastUpdated,setLastUpdated]=useState(null),[shown,setShown]=useState(50),[selected,setSelected]=useState(null),[typeFilter,setTypeFilter]=useState('all'),[ageFilter,setAgeFilter]=useState('all'),[sizeFilter,setSizeFilter]=useState('all'),[preview,setPreview]=useState(null),[previewLoading,setPreviewLoading]=useState(false);
 const refresh=useCallback(async(silent=false)=>{if(!silent)setLoading(true);const result=await callDesktop('get_vellium_live_assets');if(result?.ok){setAssets(result.assets||[]);setRunning(Boolean(result.roblox_running));setSourceFound(Boolean(result.sources?.length));setLastUpdated(new Date())}else if(!silent)notify(result?.error||'Could not read Fleasion cache');if(!silent)setLoading(false)},[notify]);
 useEffect(()=>{refresh();},[refresh]);
 useEffect(()=>{if(!auto)return;const timer=setInterval(()=>refresh(true),4000);return()=>clearInterval(timer)},[auto,refresh]);
 const typeOptions=useMemo(()=>[{value:'all',label:'All asset types',detail:`${assets.length} captured`},...[...new Set(assets.map(a=>a.type_name||'Unknown'))].sort().map(name=>({value:name,label:name,detail:`${assets.filter(a=>a.type_name===name).length} assets`}))],[assets]);
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase(),now=Date.now();return assets.filter(a=>{if(needle&&!`${a.id} ${a.type_name} ${a.url} ${a.name} ${a.creator}`.toLowerCase().includes(needle))return false;if(typeFilter!=='all'&&a.type_name!==typeFilter)return false;const size=Number(a.size)||0;if(sizeFilter==='small'&&size>=102400)return false;if(sizeFilter==='medium'&&(size<102400||size>=1048576))return false;if(sizeFilter==='large'&&size<1048576)return false;if(ageFilter!=='all'){const age=now-new Date(a.cached_at).valueOf(),limit=ageFilter==='hour'?3600000:ageFilter==='day'?86400000:604800000;if(!Number.isFinite(age)||age>limit)return false}return true})},[assets,query,typeFilter,ageFilter,sizeFilter]);
 useEffect(()=>setShown(50),[query,typeFilter,ageFilter,sizeFilter]);
 const rendered=visible.slice(0,shown);
 useEffect(()=>{if(!selected){setPreview(null);return}let live=true;setPreviewLoading(true);callDesktop('get_vellium_asset_preview',selected.id,selected.type,selected.type_name).then(result=>{if(live){setPreview(result);setPreviewLoading(false)}});return()=>{live=false}},[selected]);
 const copy=id=>{navigator.clipboard.writeText(String(id));notify(`Copied asset ${id}`)};
 const add=id=>{sessionStorage.setItem('vellium.pendingAssetId',String(id));onNavigate?.('assetProxy')};
 return <div className="view scraper-view">
  <header className="proxy-header scraper-header"><div><span className="eyebrow">Vellium Proxy</span><h1>Asset scraper</h1><p>View asset IDs captured from Roblox by Fleasion's local proxy.</p></div><div className="scraper-live"><i className={running?'active':''}/><span><strong>{running?'Roblox detected':'Waiting for Roblox'}</strong><small>{running?'Scraper monitoring cache':'Scraper idle'}</small></span></div></header>
  <section className="scraper-toolbar"><label className="scraper-search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search IDs, names, creators, types, or URLs"/></label><button className={`scraper-auto${auto?' on':''}`} onClick={()=>setAuto(value=>!value)}><span><strong>Live refresh</strong><small>{auto?'Updates automatically':'Paused'}</small></span><i><b/></i></button><button className="btn" onClick={()=>refresh()} disabled={loading}><Icon name="refresh" size={13}/>{loading?'Refreshing…':'Refresh'}</button></section>
  <section className="scraper-filters"><div><Icon name="filter" size={13}/><span>Filters</span></div><CustomSelect compact searchable value={typeFilter} options={typeOptions} onChange={setTypeFilter}/><CustomSelect compact value={ageFilter} options={[{value:'all',label:'Any capture time'},{value:'hour',label:'Last hour'},{value:'day',label:'Last 24 hours'},{value:'week',label:'Last 7 days'}]} onChange={setAgeFilter}/><CustomSelect compact value={sizeFilter} options={[{value:'all',label:'Any file size'},{value:'small',label:'Under 100 KB'},{value:'medium',label:'100 KB – 1 MB'},{value:'large',label:'Over 1 MB'}]} onChange={setSizeFilter}/>{(typeFilter!=='all'||ageFilter!=='all'||sizeFilter!=='all')&&<button onClick={()=>{setTypeFilter('all');setAgeFilter('all');setSizeFilter('all')}}><Icon name="x" size={12}/>Clear filters</button>}</section>
  <section className="scraper-stats"><div><span>Captured assets</span><strong>{assets.length.toLocaleString()}</strong></div><div><span>Visible results</span><strong>{visible.length.toLocaleString()}</strong></div><div><span>Cache source</span><strong>{sourceFound?'Connected':'Not found'}</strong></div><div><span>Last updated</span><strong>{lastUpdated?lastUpdated.toLocaleTimeString():'—'}</strong></div></section>
  <section className="scraper-list-shell"><div className="scraper-list-head"><span>Asset</span><span>Type</span><span>Source</span><span>Captured</span><span>Size</span><span/></div>{visible.length?<div className="scraper-list" onScroll={e=>{const el=e.currentTarget;if(el.scrollTop+el.clientHeight>=el.scrollHeight-100)setShown(count=>Math.min(count+50,visible.length))}}>{rendered.map((asset,index)=><article className="scraper-row" key={`${asset.type}-${asset.id}-${index}`}><div className="scraper-id"><div className="scraper-thumb"><Icon name={['Image','Decal','TexturePack'].includes(asset.type_name)?'image':'box'} size={14}/></div><span><strong>{asset.name||asset.id}</strong><small>{asset.name?asset.id:'Roblox asset'}</small></span></div><span className="scraper-type">{asset.type_name}<small>Type {asset.type||'—'}</small></span><code title={asset.url}>{asset.creator||asset.url||'Captured response'}</code><span title={asset.cached_at}>{formatTime(asset.cached_at)}</span><span>{formatBytes(asset.size)}</span><div className="proxy-row-actions"><InfoTooltip content="View asset details"><button onClick={()=>setSelected(asset)}><Icon name="eye" size={13}/></button></InfoTooltip><InfoTooltip content="Copy asset ID"><button onClick={()=>copy(asset.id)}><Icon name="copy" size={13}/></button></InfoTooltip><InfoTooltip content="Add as a replacement"><button onClick={()=>add(asset.id)}><Icon name="plus" size={13}/></button></InfoTooltip></div></article>)}{shown<visible.length&&<div className="scraper-load-note">Scroll to load 50 more · {visible.length-shown} remaining</div>}</div>:<div className="proxy-empty"><span><Icon name="database" size={22}/></span><h2>{loading?'Reading Fleasion cache':'No assets match these filters'}</h2><p>{assets.length?'Clear a filter or try another search.':'Start Vellium Proxy, launch Roblox, and join a game. Captured assets will appear here automatically.'}</p>{!loading&&<button className="btn" onClick={()=>refresh()}><Icon name="refresh" size={13}/>Check again</button>}</div>}</section>
  <Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title="Asset details" subtitle="Captured by the Vellium Proxy scraper" width="560px" footer={<><button className="btn" onClick={()=>copy(selected?.id)}><Icon name="copy" size={13}/>Copy ID</button><button className="btn primary" onClick={()=>add(selected?.id)}><Icon name="plus" size={13}/>Add replacement</button></>}><div className="scraper-detail-card"><div className="scraper-detail-preview">{preview?.previewable?<img src={preview.data_url} alt={selected?`Asset ${selected.id}`:''}/>:<span><Icon name={previewLoading?'refresh':'box'} size={30}/><small>{previewLoading?'Loading cached preview…':preview?.reason||'Preview unavailable for this asset type'}</small></span>}</div><div className="scraper-detail-title"><div><span>{selected?.type_name||'Unknown asset'}</span><strong>{selected?.name||selected?.id}</strong>{selected?.name&&<small>ID {selected.id}</small>}</div><span className="scraper-type-badge">Type {selected?.type||'—'}</span></div><dl><div><dt>Asset ID</dt><dd>{selected?.id}</dd></div><div><dt>Asset type</dt><dd>{selected?.type_name||'Unknown'}</dd></div><div><dt>Creator</dt><dd>{selected?.creator||'Unknown'}</dd></div><div><dt>File size</dt><dd>{formatBytes(selected?.size)}</dd></div><div><dt>Captured</dt><dd>{formatTime(selected?.cached_at)}</dd></div><div className="wide"><dt>Source URL</dt><dd title={selected?.url}>{selected?.url||'Captured response'}</dd></div></dl></div></Modal>
 </div>
}
