import { useState } from 'react';
import { Icon } from '../Icons';
import { SectionIntro } from './SiteChrome';

const features=[['search','Flag intelligence','Search known flags with type and description context.'],['process','Process control','Select a client, see attachment state, detach, or end it.'],['branch','Offset sources','Use current or custom versions and manage source URLs.'],['settings','Theme studio','Build palettes, backgrounds, icons, and button shapes.'],['terminal','Docked console','Inspect searchable runtime output inside the workspace.'],['refresh','Safe recovery','Restore local state and recover from interface failures.']];
const questions=[['What does the download include?','A standalone Windows executable with the application runtime packaged with it.'],['Where are themes saved?','Locally under Meow Ware in LocalAppData.'],['Can I use custom offsets?','Yes. Sources supports current definitions and compatible custom URLs.'],['What systems are supported?','Current 64-bit Windows 10 and Windows 11 systems.']];

export function Metrics(){return <section className="metrics"><b>14,000+<small>Known flags</small></b><b>50<small>Theme icons</small></b><b>Local<small>Theme storage</small></b><b>Live<small>Process status</small></b></section>}
export function FeatureSection(){return <section id="features" className="section"><SectionIntro tag="CAPABILITIES" title="Designed like a utility, not a toy." text="Every tool has a clear place and a visible state."/><div className="features">{features.map(([icon,title,text],index)=><article key={title}><small>0{index+1}</small><Icon name={icon}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>}
export function UpdateSection(){return <section id="new" className="section"><SectionIntro tag="VERSION 1.3" title="A more personal workspace." text="Customization without giving up clarity."/><div className="updates">{[['settings','Complete theme studio'],['layers','Animated backgrounds'],['refresh','Anti-crash recovery']].map(([icon,title])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>Thoughtful controls, local persistence, and restrained motion built into the same focused interface.</p></article>)}</div></section>}
export function FAQSection(){const[active,setActive]=useState(0);return <section id="faq" className="section faq"><SectionIntro tag="FAQ" title="Before you download."/><div>{questions.map(([question,answer],index)=><article key={question} className={active===index?'open':''}><button onClick={()=>setActive(active===index?-1:index)}>{question}<Icon name={active===index?'minus':'plus'}/></button><div><p>{answer}</p></div></article>)}</div></section>}
export function DownloadPanel(){return <section className="final"><img src="/meow-ware-icon.png" alt=""/><small>MEOW WARE 1.3</small><h2>Your FastFlags.<br/>One calm workspace.</h2><a className="cta" href="./Meow-Ware-v1.3.exe" download>Download Meow Ware <Icon name="download" size={13}/></a></section>}
