import { useEffect, useState } from 'react';
import { Icon } from '../components/Icons';
import { callDesktop } from '../lib/desktopApi';
import { VersionBadge } from '../components/VersionStatus';
import { DowngradeNotice } from '../components/VersionStatus';
import CustomSelect from '../components/CustomSelect';

const short=v=>v?String(v).replace(/^version-/,'').slice(0,12):'—';
export default function BuildsView({notify}){
 const [data,setData]=useState({versions:[]}),[loading,setLoading]=useState(true),[target,setTarget]=useState(''),[ack,setAck]=useState(false),[progress,setProgress]=useState(null);
 const refresh=async()=>{setLoading(true);const value=await callDesktop('get_roblox_build_options');if(value?.ok!==false)setData(value||{versions:[]});setLoading(false)};useEffect(()=>{refresh()},[]);
 const choose=async()=>{const r=await callDesktop('choose_roblox_install_folder');if(r?.ok){notify('Roblox build folder updated');refresh()}else if(!r?.cancelled)notify(r?.error||'Could not select folder')};
 const kill=async()=>{const r=await callDesktop('kill_roblox_now');notify(r?.ok===false?r.error:r?.message||'Roblox stopped')};
 const options=(data.versions||[]).map(item=>{const version=typeof item==='string'?item:item.version;return{value:version,label:version,detail:typeof item==='object'&&item.created_at?new Date(item.created_at).toLocaleDateString():''}});
 const older=Boolean(target&&data.latest_production&&target!==data.latest_production);
 const download=async()=>{const mode=target?'custom':'latest';const r=await callDesktop('start_roblox_version_download',mode,target,ack);if(['started','already_running'].includes(r?.state))setProgress({state:'running',progress:0,message:r.message});else notify(r?.message||'Could not start download')};
 useEffect(()=>{if(progress?.state!=='running')return;const timer=setInterval(async()=>{const p=await callDesktop('get_roblox_fix_progress');if(!p)return;setProgress(p);if(p.state==='done'){clearInterval(timer);notify(p.message||'Build installed');refresh()}else if(['failed','cancelled'].includes(p.state)){clearInterval(timer);notify(p.message||'Download failed')}},500);return()=>clearInterval(timer)},[progress?.state]);
 return <div className="builds-view manager-view view"><header className="manager-header"><div><span>CLIENT MANAGEMENT</span><h1>Roblox Builds</h1><p>Download, organize, and choose the client version used by Vellium.</p></div><div><button className="btn danger" onClick={kill}><Icon name="x" size={12}/> Kill Roblox</button><button className="btn" onClick={refresh}><Icon name="refresh" size={12}/> Refresh</button></div></header><div className="builds-overview"><article><small>Installed</small><strong>{short(data.installed_version)}</strong><VersionBadge kind="installed"/></article><article><small>Default launch</small><strong>{short(data.preferred_version)}</strong><span>{data.preferred_path||'Automatic selection'}</span></article><article><small>Latest CDN</small><strong>{short(data.latest_production)}</strong><VersionBadge kind="latest"/></article></div><section className="builds-location"><span><Icon name="folder" size={17}/></span><div><small>INSTALL LOCATION</small><strong>{data.install_root||'Roblox default versions folder'}</strong><p>New downloaded builds are installed here and selected as the Launch Roblox default.</p></div><button className="btn primary" onClick={choose}><Icon name="folder" size={12}/> Choose folder</button></section><section className="builds-downloader"><header><div><strong>Build downloader</strong><small>{loading?'Loading catalog…':`${options.length} client versions available`}</small></div><VersionBadge kind={older?'downgrade':'latest'}/></header><CustomSelect searchable value={target} onChange={value=>{setTarget(value);setAck(false)}} options={options} label={`Latest production · ${short(data.latest_production)}`}/>{older&&<DowngradeNotice compact acknowledged={ack} onAcknowledge={setAck}/>} {progress?.state==='running'&&<div className="build-progress"><div><span>{progress.message}</span><strong>{progress.progress||0}%</strong></div><i><b style={{width:`${Math.max(2,progress.progress||0)}%`}}/></i></div>}<button className="btn primary builds-download" disabled={progress?.state==='running'||(older&&!ack)} onClick={download}><Icon name="download" size={12}/>{progress?.state==='running'?'Installing…':target?'Download selected build':'Download latest build'}</button></section><section className="builds-catalog"><header><div><strong>Available versions</strong><small>Recent catalog entries</small></div></header><div>{(data.versions||[]).slice(0,12).map((item,index)=>{const v=typeof item==='string'?item:item.version;return <article key={v} onClick={()=>{setTarget(v);setAck(false)}}><span><strong>{short(v)}</strong><small>{typeof item==='object'&&item.created_at?new Date(item.created_at).toLocaleDateString():'Roblox client build'}</small></span>{index===0?<VersionBadge kind="latest"/>:<VersionBadge kind="downgrade"/>}</article>})}</div></section></div>;
}
